import logo from "../assets/mask-group.png";

export const DATA = {
    buy: [
        {
            id: "0",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            expiry: "Expiry: 3h 14m",
            liked: true,
        },
        {
            id: "1",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            expiry: "Expiry: 3h 14m",
            liked: true,
        },
        {
            id: "2",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            expiry: "Expiry: 3h 14m",
            liked: true,
        },
        {
            id: "3",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            expiry: "Expiry: 3h 14m",
            liked: true,
        },
        {
            id: "4",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            expiry: "Expiry: 3h 14m",
            liked: true,
        },
        {
            id: "5",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            expiry: "Expiry: 3h 14m",
            liked: true,
        },
        {
            id: "6",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            expiry: "Expiry: 3h 14m",
            liked: true,
        },
        {
            id: "7",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            expiry: "Expiry: 3h 14m",
            liked: true,
        },
        {
            id: "8",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            expiry: "Expiry: 3h 14m",
            liked: true,
        },
    ],

    trade: [
        {
            id: "0",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            liked: false,
        },
        {
            id: "1",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            liked: false,
        },
        {
            id: "2",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            liked: true,
        },
        {
            id: "3",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            liked: true,
        },
        {
            id: "4",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            liked: true,
        },
        {
            id: "5",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            liked: true,
        },
        {
            id: "6",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            liked: true,
        },
        {
            id: "7",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            liked: true,
        },
        {
            id: "8",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            liked: true,
        },
    ],
    sell: [
        {
            id: "0",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            expiry: "Expiry: 3h 14m",
            liked: false,
        },
        {
            id: "1",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            expiry: "Expiry: 3h 14m",
            liked: false,
        },
        {
            id: "2",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            expiry: "Expiry: 3h 14m",
            liked: false,
        },
        {
            id: "3",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            expiry: "Expiry: 3h 14m",
            liked: true,
        },
        {
            id: "4",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            expiry: "Expiry: 3h 14m",
            liked: true,
        },
        {
            id: "5",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            expiry: "Expiry: 3h 14m",
            liked: true,
        },
        {
            id: "6",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            expiry: "Expiry: 3h 14m",
            liked: true,
        },
        {
            id: "7",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            expiry: "Expiry: 3h 14m",
            liked: true,
        },
        {
            id: "8",
            img: require("../assets/mask-group.png"),
            title: "Nike Air Jordans 2015",
            distance: "0.32km Away",
            expiry: "Expiry: 3h 14m",
            liked: true,
        },
    ],
};
